export interface FontOption {
  name: string
  family: string
  category: "sans-serif" | "serif" | "monospace"
}

export const fontOptions: FontOption[] = [
  { name: "Inter", family: "Inter", category: "sans-serif" },
  { name: "Roboto", family: "Roboto", category: "sans-serif" },
  { name: "Open Sans", family: "Open Sans", category: "sans-serif" },
  { name: "Lato", family: "Lato", category: "sans-serif" },
  { name: "Poppins", family: "Poppins", category: "sans-serif" },
  { name: "Montserrat", family: "Montserrat", category: "sans-serif" },
  { name: "Nunito", family: "Nunito", category: "sans-serif" },
  { name: "Raleway", family: "Raleway", category: "sans-serif" },
  { name: "Source Sans 3", family: "Source Sans 3", category: "sans-serif" },
  { name: "Work Sans", family: "Work Sans", category: "sans-serif" },
  { name: "DM Sans", family: "DM Sans", category: "sans-serif" },
  { name: "Plus Jakarta Sans", family: "Plus Jakarta Sans", category: "sans-serif" },
  { name: "Playfair Display", family: "Playfair Display", category: "serif" },
  { name: "Merriweather", family: "Merriweather", category: "serif" },
  { name: "Lora", family: "Lora", category: "serif" },
  { name: "PT Serif", family: "PT Serif", category: "serif" },
  { name: "Libre Baskerville", family: "Libre Baskerville", category: "serif" },
  { name: "Bebas Neue", family: "Bebas Neue", category: "sans-serif" },
  { name: "Orbitron", family: "Orbitron", category: "sans-serif" },
  { name: "Exo 2", family: "Exo 2", category: "sans-serif" },
  { name: "Outfit", family: "Outfit", category: "sans-serif" },
  { name: "Space Mono", family: "Space Mono", category: "monospace" },
  { name: "JetBrains Mono", family: "JetBrains Mono", category: "monospace" },
  { name: "Fira Code", family: "Fira Code", category: "monospace" },
]

export function getFontFallback(fontName: string): string {
  const font = fontOptions.find((f) => f.name === fontName)
  return font?.category || "sans-serif"
}

export function buildGoogleFontsUrl(fonts: string[]): string | null {
  const unique = [...new Set(fonts.filter((f) => f && f !== "Inter"))]
  if (unique.length === 0) return null
  const families = unique.map((f) => `family=${f.replace(/ /g, "+")}:wght@300;400;500;600;700`).join("&")
  return `https://fonts.googleapis.com/css2?${families}&display=swap`
}

export interface ThemePreset {
  name: string
  description: string
  settings: Record<string, string>
}

export const themePresets: ThemePreset[] = [
  /* ── Light Presets ── */
  {
    name: "Modern",
    description: "Clean and professional with sharp edges",
    settings: {
      theme_mode: "light",
      font_heading: "Inter",
      font_body: "Inter",
      primary_color: "#000000",
      secondary_color: "#4b5563",
      accent_color: "#2563eb",
      button_bg_color: "#000000",
      button_text_color: "#ffffff",
      background_color: "#ffffff",
      foreground_color: "#171717",
      muted_color: "#f3f4f6",
      border_color: "#e5e7eb",
      dark_background_color: "#0a0a0a",
      dark_foreground_color: "#f5f5f5",
      dark_muted_color: "#1f2937",
      dark_border_color: "#374151",
      border_radius: "medium",
      shadow_depth: "subtle",
    },
  },
  {
    name: "Warm",
    description: "Earth tones with classic serif headings",
    settings: {
      theme_mode: "light",
      font_heading: "Lora",
      font_body: "Source Sans 3",
      primary_color: "#92400e",
      secondary_color: "#78716c",
      accent_color: "#b45309",
      button_bg_color: "#92400e",
      button_text_color: "#ffffff",
      background_color: "#fefdf8",
      foreground_color: "#292524",
      muted_color: "#f5f0e8",
      border_color: "#d6d3d1",
      dark_background_color: "#1c1917",
      dark_foreground_color: "#fafaf9",
      dark_muted_color: "#292524",
      dark_border_color: "#44403c",
      border_radius: "small",
      shadow_depth: "subtle",
    },
  },
  {
    name: "Bold",
    description: "Vibrant blue with strong rounded elements",
    settings: {
      theme_mode: "light",
      font_heading: "Poppins",
      font_body: "Poppins",
      primary_color: "#2563eb",
      secondary_color: "#64748b",
      accent_color: "#7c3aed",
      button_bg_color: "#2563eb",
      button_text_color: "#ffffff",
      background_color: "#ffffff",
      foreground_color: "#0f172a",
      muted_color: "#f1f5f9",
      border_color: "#e2e8f0",
      dark_background_color: "#020617",
      dark_foreground_color: "#f8fafc",
      dark_muted_color: "#1e293b",
      dark_border_color: "#334155",
      border_radius: "large",
      shadow_depth: "bold",
    },
  },
  {
    name: "Minimal",
    description: "Ultra-clean with muted tones and no shadows",
    settings: {
      theme_mode: "light",
      font_heading: "DM Sans",
      font_body: "DM Sans",
      primary_color: "#18181b",
      secondary_color: "#71717a",
      accent_color: "#a1a1aa",
      button_bg_color: "#18181b",
      button_text_color: "#ffffff",
      background_color: "#ffffff",
      foreground_color: "#18181b",
      muted_color: "#fafafa",
      border_color: "#f4f4f5",
      dark_background_color: "#09090b",
      dark_foreground_color: "#fafafa",
      dark_muted_color: "#18181b",
      dark_border_color: "#27272a",
      border_radius: "small",
      shadow_depth: "none",
    },
  },
  {
    name: "Elegant",
    description: "Refined serif headings with navy tones",
    settings: {
      theme_mode: "light",
      font_heading: "Playfair Display",
      font_body: "Lato",
      primary_color: "#1e3a5f",
      secondary_color: "#64748b",
      accent_color: "#c5975b",
      button_bg_color: "#1e3a5f",
      button_text_color: "#ffffff",
      background_color: "#ffffff",
      foreground_color: "#1e293b",
      muted_color: "#f8fafc",
      border_color: "#e2e8f0",
      dark_background_color: "#0c1222",
      dark_foreground_color: "#f1f5f9",
      dark_muted_color: "#1e293b",
      dark_border_color: "#334155",
      border_radius: "small",
      shadow_depth: "subtle",
    },
  },
  {
    name: "Playful",
    description: "Colorful and rounded with fun energy",
    settings: {
      theme_mode: "light",
      font_heading: "Nunito",
      font_body: "Nunito",
      primary_color: "#7c3aed",
      secondary_color: "#6b7280",
      accent_color: "#ec4899",
      button_bg_color: "#7c3aed",
      button_text_color: "#ffffff",
      background_color: "#ffffff",
      foreground_color: "#1f2937",
      muted_color: "#faf5ff",
      border_color: "#e9d5ff",
      dark_background_color: "#0f0520",
      dark_foreground_color: "#f5f3ff",
      dark_muted_color: "#1e1033",
      dark_border_color: "#4c1d95",
      border_radius: "full",
      shadow_depth: "medium",
    },
  },
  /* ── Dark Presets ── */
  {
    name: "Midnight",
    description: "Deep navy with cool blue accents",
    settings: {
      theme_mode: "dark",
      font_heading: "Inter",
      font_body: "Inter",
      primary_color: "#3b82f6",
      secondary_color: "#94a3b8",
      accent_color: "#60a5fa",
      button_bg_color: "#3b82f6",
      button_text_color: "#ffffff",
      background_color: "#ffffff",
      foreground_color: "#0f172a",
      muted_color: "#f1f5f9",
      border_color: "#e2e8f0",
      dark_background_color: "#0f172a",
      dark_foreground_color: "#e2e8f0",
      dark_muted_color: "#1e293b",
      dark_border_color: "#334155",
      border_radius: "medium",
      shadow_depth: "subtle",
    },
  },
  {
    name: "Carbon",
    description: "Pure dark with minimal contrast",
    settings: {
      theme_mode: "dark",
      font_heading: "DM Sans",
      font_body: "DM Sans",
      primary_color: "#ffffff",
      secondary_color: "#a1a1aa",
      accent_color: "#71717a",
      button_bg_color: "#ffffff",
      button_text_color: "#09090b",
      background_color: "#ffffff",
      foreground_color: "#18181b",
      muted_color: "#f4f4f5",
      border_color: "#e4e4e7",
      dark_background_color: "#09090b",
      dark_foreground_color: "#fafafa",
      dark_muted_color: "#18181b",
      dark_border_color: "#27272a",
      border_radius: "small",
      shadow_depth: "none",
    },
  },
  {
    name: "Ember",
    description: "Dark with warm amber and orange glow",
    settings: {
      theme_mode: "dark",
      font_heading: "Source Sans 3",
      font_body: "Source Sans 3",
      primary_color: "#f59e0b",
      secondary_color: "#a8a29e",
      accent_color: "#ef4444",
      button_bg_color: "#f59e0b",
      button_text_color: "#1c1917",
      background_color: "#fefdf8",
      foreground_color: "#292524",
      muted_color: "#f5f0e8",
      border_color: "#d6d3d1",
      dark_background_color: "#1c1917",
      dark_foreground_color: "#fafaf9",
      dark_muted_color: "#292524",
      dark_border_color: "#44403c",
      border_radius: "medium",
      shadow_depth: "medium",
    },
  },
  {
    name: "Neon",
    description: "Dark with electric neon highlights",
    settings: {
      theme_mode: "dark",
      font_heading: "Space Mono",
      font_body: "Inter",
      primary_color: "#22d3ee",
      secondary_color: "#94a3b8",
      accent_color: "#a78bfa",
      button_bg_color: "#22d3ee",
      button_text_color: "#020617",
      background_color: "#ffffff",
      foreground_color: "#0f172a",
      muted_color: "#f1f5f9",
      border_color: "#e2e8f0",
      dark_background_color: "#020617",
      dark_foreground_color: "#e2e8f0",
      dark_muted_color: "#0f172a",
      dark_border_color: "#1e293b",
      border_radius: "small",
      shadow_depth: "subtle",
    },
  },
  {
    name: "Laboratory",
    description: "Deep navy with electric blue and silver accents",
    settings: {
      theme_mode: "dark",
      font_heading: "Montserrat",
      font_body: "Inter",
      primary_color: "#2a8ef0",
      secondary_color: "#8a9bb8",
      accent_color: "#5bbfff",
      button_bg_color: "#2a8ef0",
      button_text_color: "#ffffff",
      background_color: "#f0f4f8",
      foreground_color: "#0a1628",
      muted_color: "#e1e8f0",
      border_color: "#c8d3e0",
      dark_background_color: "#0a1628",
      dark_foreground_color: "#dce5f0",
      dark_muted_color: "#0f2240",
      dark_border_color: "#1a3558",
      border_radius: "medium",
      shadow_depth: "subtle",
    },
  },
  {
    name: "Lab Rats",
    description: "Dark theme with neon green accents — the Lab Rats brand",
    settings: {
      theme_mode: "dark",
      font_heading: "Exo 2",
      font_body: "DM Sans",
      primary_color: "#00ff41",
      secondary_color: "#a0a0a0",
      accent_color: "#00ff41",
      button_bg_color: "#00ff41",
      button_text_color: "#000000",
      button_style: "filled",
      product_button_bg_color: "#00ff41",
      product_button_text_color: "#000000",
      product_button_style: "filled",
      background_color: "#ffffff",
      foreground_color: "#111111",
      muted_color: "#f5f5f5",
      border_color: "#e5e5e5",
      dark_background_color: "#0d0d0d",
      dark_foreground_color: "#ffffff",
      dark_muted_color: "#1a1a1a",
      dark_border_color: "#2a2a2a",
      header_bg_color: "#0d0d0d",
      header_nav_color: "#cccccc",
      header_nav_hover_color: "#00ff41",
      header_icon_color: "#cccccc",
      header_icon_hover_color: "#00ff41",
      header_user_bg_color: "#00ff41",
      header_user_text_color: "#000000",
      header_cart_badge_bg_color: "#00ff41",
      header_cart_badge_text_color: "#000000",
      footer_bg_color: "#111111",
      footer_heading_color: "#00ff41",
      footer_link_color: "#a0a0a0",
      footer_link_hover_color: "#00ff41",
      product_card_style: "boxed",
      product_card_bg_color: "#1a1a1a",
      product_card_shadow: "none",
      border_radius: "full",
      shadow_depth: "none",
    },
  },
  {
    name: "Enoch Labs",
    description: "Navy and cyan inspired by the Enoch Labs brand",
    settings: {
      theme_mode: "light",
      font_heading: "Montserrat",
      font_body: "Inter",
      primary_color: "#1B2D45",
      secondary_color: "#5a6d85",
      accent_color: "#2E9AD0",
      button_bg_color: "#2E9AD0",
      button_text_color: "#ffffff",
      background_color: "#ffffff",
      foreground_color: "#1B2D45",
      muted_color: "#f0f6fa",
      border_color: "#d4e1ec",
      dark_background_color: "#0d1a2a",
      dark_foreground_color: "#e0e8f0",
      dark_muted_color: "#142338",
      dark_border_color: "#1e3652",
      border_radius: "medium",
      shadow_depth: "subtle",
    },
  },
]

export const radiusOptions = [
  { label: "None (0px)", value: "none" },
  { label: "Small (4px)", value: "small" },
  { label: "Medium (8px)", value: "medium" },
  { label: "Large (12px)", value: "large" },
  { label: "Full (pill)", value: "full" },
]

export const shadowOptions = [
  { label: "None", value: "none" },
  { label: "Subtle", value: "subtle" },
  { label: "Medium", value: "medium" },
  { label: "Bold", value: "bold" },
]

export const radiusValues: Record<string, string> = {
  none: "0px",
  small: "4px",
  medium: "8px",
  large: "12px",
  full: "9999px",
}

export const shadowValues: Record<string, string> = {
  none: "none",
  subtle: "0 1px 2px rgba(0,0,0,0.05)",
  medium: "0 4px 6px rgba(0,0,0,0.07)",
  bold: "0 10px 25px rgba(0,0,0,0.1)",
}
